### ISSUE TITLE
Help: Linker Error

### ISSUE THREAD

**Issue by gtotoy** [taylor001/crown#46]
Hi,
 I was trying to make the engine using visual studio 2013 with directx june 2010 and Physx 3.3.1. But when it was on the linker phase to create crown-release-32.exe I get an error.
![linker error](https://cloud.githubusercontent.com/assets/2191588/6231977/126893b8-b697-11e4-9b26-f631c93cb8e0.png)
![built](https://cloud.githubusercontent.com/assets/2191588/6232014/72a5ad7e-b697-11e4-8323-29d1d9eb5c0a.png)
![error](https://cloud.githubusercontent.com/assets/2191588/6232016/783d2334-b697-11e4-9433-bc1c53d61f4a.png)
Do you know what could be the problem?

**Comment by mtwilliams** [comment]
Looks like you're failing to link to `lua51` — is LuaJIT built?

Run `DIR` on `third/luajit` and paste the output here.

**Comment by gtotoy** [comment]
Hi Michael,

This is the output
![luajit](https://cloud.githubusercontent.com/assets/2191588/6405088/2967e6c4-bded-11e4-8057-19d87ff81a28.png)

**Comment by mtwilliams** [comment]
Hmm.

Is `CROWN_INSTALL_DIR` set?

**Comment by gtotoy** [comment]
No, it wasn't set, but I found the problem. The lua51.dll was built for x64 platform even with make windows-release32. I tried make windows-development64 and it worked. However, I had to manually create crown/bin/win64 folder.
![built](https://cloud.githubusercontent.com/assets/2191588/6424152/fd231500-bec0-11e4-9b95-dfd1908f34bc.png)

Now, I have another question. How can I run 01.hello-world sample? Could you help me?

**Comment by mtwilliams** [comment]
Do something along the lines of: `crown-development-64.exe --source-dir samples/01.hello-world --bundle-dir compiled --platform windows --compile --continue`

**Comment by gtotoy** [comment]
I got this
![hello-world](https://cloud.githubusercontent.com/assets/2191588/6426589/b2fb6070-bf30-11e4-9f61-c78b497b75d9.png)

**Comment by lundmark** [comment]
Try starting the executable through a debugger instead so that you can see
what the reason behind the crash is.

/S

**Comment by mikymod** [comment]
Hi gtotoy, can you build in debug mode and provide logs? thank you ^^

**Comment by taylor001** [comment]
You have to use the appropriate Visual Studio Tools prompt in order for luajit to correctly select the target platform under windows. Building luajit with genie would solve the problem.

**Comment by taylor001** [comment]
Crash is due to wrong shader version passed to the renderer. I temporarily forced D3D9 on windows.

**Comment by gtotoy** [comment]
How can I force to D3D9? It crashes in this line
DX_CHECK(s_renderD3D11->m_device->CreateVertexShader(code, shaderSize, NULL, &m_vertexShader) );
inside
void ShaderD3D11::create(const Memory* _mem);

**Comment by taylor001** [comment]
Just git pull. :)

**Comment by gtotoy** [comment]
Now, I get this problem. Do you have an idea?
![compiler](https://cloud.githubusercontent.com/assets/2191588/6658582/f444717c-cb3b-11e4-9bf5-e72969ad54fb.png)

**Comment by taylor001** [comment]
Source and bundle directories must differ, also, resource types are determined by file extension so you cannot have a .txt file in your source directory.

**Comment by gtotoy** [comment]
It worked. Thanks :)
![sample-hello](https://cloud.githubusercontent.com/assets/2191588/6666661/5c9f008e-cbb4-11e4-82b1-5506529ff043.png)

**Comment by taylor001** [comment]
:+1:
