### ISSUE TITLE
Valgrind output is absolutely terrifying

### ISSUE THREAD

**Issue by Kingsquee** [taylor001/crown#57]
[absolutely terrifying](https://gist.githubusercontent.com/Kingsquee/b6656b05f030190efea7/raw/3b5dfbb8c4e253d5cd43e06be8d2557b678c1177/absolutely%2520terrifying)

Fedora 23, 64 bit

**Comment by taylor001** [comment]
Engine crashed on shader load, that's a perfectly reasonable valgrind output.

**Comment by Kingsquee** [comment]
Well okay, but even with the latest master I'm getting rather noisy valgrind results.

[output from a successful valgrind run: ERROR SUMMARY: **176092** errors from 71 contexts (suppressed: 0 from 0)](https://gist.github.com/anonymous/84b2830ed31fa2bf8299)
[output from crash during valgrind run: ERROR SUMMARY: **25873** errors from 1376 contexts (suppressed: 0 from 0)](https://gist.github.com/anonymous/7138353877c0c75979f)

Even if some of them are false positives, this makes detecting genuine leaks a terrible chore.
