### ISSUE TITLE
assertion failed: compiler not found

### ISSUE THREAD

**Issue by Kingsquee** [taylor001/crown#58]
Fedora 23, 64bit

```
$ ./crown-debug-64 --source-dir /home/kingsley/Downloads/crown/samples/01-physics/ --bundle-dir /tmp --compile --platform linux --continue
eac0b497876adedf-424247333dfb94b1 <= grid.material
eac0b497876adedf-8d4c847f2ad44b96 <= notexture.material
48ff313713a997a1-ce20b2a5524dca1c <= skydome.mesh
48ff313713a997a1-4362dbe08c02948a <= cube.mesh
e0a48d0be9a7453f-4362dbe08c02948a <= cube.unit
e0a48d0be9a7453f-3bc32bb81c975af2 <= cube_prefab.unit
eac0b497876adedf-ce20b2a5524dca1c <= skydome.material
a14e8dfa2cd117e2-eb68aaa83687073a <= lua/camera.lua
a14e8dfa2cd117e2-9dea40fdc2245efc <= lua/game.lua
a14e8dfa2cd117e2-5bfc062cf75525e5 <= lua/class.lua
e0a48d0be9a7453f-5d4e7845bfca884c <= ramp.unit
e0a48d0be9a7453f-9899ff2b9397a399 <= plane.unit
e0a48d0be9a7453f-ce20b2a5524dca1c <= skydome.unit
cd4238c6a0c69e32-424247333dfb94b1 <= grid.texture
e0a48d0be9a7453f-6096f939f031e445 <= cube_prefab2.unit
7a4202f968757bc9-5e02bba66d851216 <= core/shaders/.default.shader.swp

Assertion failed: sort_map::has(_compilers, type)
	Compiler not found

	In: ../../../src/resource/bundle_compiler.cpp:176
Stacktrace:
	[1] ./crown-debug-64() [0x4d93a3]
	[2] ./crown-debug-64: (crown::error::abort(char const*, int, char const*, ...))+0xa8 in /home/kingsley/Downloads/crown/build/projects/linux/../../../src/core/error/error.cpp:31
	[3] ./crown-debug-64: (crown::BundleCompiler::compile(crown::StringId64, char const*, crown::CompileOptions&))+0x54 in /home/kingsley/Downloads/crown/build/projects/linux/../../../src/resource/bundle_compiler.cpp:178
	[4] ./crown-debug-64: (crown::BundleCompiler::compile(char const*, char const*, char const*))+0x232 in /home/kingsley/Downloads/crown/build/projects/linux/../../../src/resource/bundle_compiler.cpp:114
	[5] ./crown-debug-64: (crown::BundleCompiler::compile_all(char const*))+0x2c1 in /home/kingsley/Downloads/crown/build/projects/linux/../../../src/resource/bundle_compiler.cpp:154
	[6] ./crown-debug-64: (crown::bundle_compiler::main(bool, bool, char const*))+0x37 in /home/kingsley/Downloads/crown/build/projects/linux/../../../src/resource/bundle_compiler.cpp:224
	[7] ./crown-debug-64: (main)+0xe3 in /home/kingsley/Downloads/crown/build/projects/linux/../../../src/main/main_linux.cpp:738
	[8] /lib64/libc.so.6: (__libc_start_main)+0xf0 in ??:0
	[9] ./crown-debug-64: (_start)+0x29 in ??:?

```

**Comment by taylor001** [comment]
Crown just asserts() on unknown file extensions. I've added some more to the "ignore list": dc376fd5b51e12aab11e098b2b24bc41a87c0358

**Comment by Kingsquee** [comment]
Some trivial fiddling with the shaders managed to break it again: 
```
...
38fac56578675f33-5e02bba66d851216 <= core/shaders/.default.shader.swo

Assertion failed: sort_map::has(_compilers, type)
	Compiler not found
...
```

Wouldn't it make more sense to ignore all file types but the types we're looking for, listed in a bundlecompiler config file? It'd be much less a game of cat and mouse.

**Comment by mtwilliams** [comment]
The issue I see with that @Kingsquee, is if you off-by-one a file extension, you'll waste time figuring out why your shader can't be found.

A better solution (from a UX point-of-view) would be checking the [distance](https://en.wikipedia.org/wiki/Edit_distance) between file extensions and known file extensions. Perhaps with an ignore list for actually useless files.

Then again, you should be putting non-essential data elsewhere.

**Comment by Kingsquee** [comment]
@mtwilliams If I mistype a file extension, I'd expect it to not load. Having the tool try to work with my incompetence rather than encourage correctness can only end terribly.

Edit distance for file extensions would be excellent for compile errors, e.g. `Error: Found "cube.ubit", did you mean "cube.unit"?` Totally with you on that.

**Comment by mtwilliams** [comment]
@Kingsquee only meant the latter case...

**Comment by Kingsquee** [comment]
@mtwilliams Cool, wasn't sure which you meant. :+1:

**Comment by taylor001** [comment]
I think @mtwilliams is right: silently skipping unknown file extensions is out of question, same for "warnings" as they tend to be ignored. Fail-fast and you can forget a whole class of potential issues.
At the same time, I do not want to force people to not use their favorite filesystem-cluttering programs. Probably, a .gitignore-like config file is the best option.

**Comment by Kingsquee** [comment]
Yeah, you're right. A whitelist would be could always be added that if the team find it necessary. Can't say the same for the other way around!

Should the issue be closed, or leave it open until the config is added?

**Comment by taylor001** [comment]
I think I'll keep it as a reminder, thanks. :)

**Comment by taylor001** [comment]
Added basic .bundleignore support: d27503a1fd1d14bf6bd335cf5f91de7a70463c2d
It's similar to .gitignore:

    # Comment.
  
    # Blank lines are skipped.
    # Everything else is simple glob pattern (*, ?).
    *.txt

I'll add a reference page to the docs.

**Comment by mtwilliams** [comment]
:+1:
