### ISSUE TITLE
Pepper Binary doesn't work properly, Tools Do Not Build on Ubuntu x64

### ISSUE THREAD

**Issue by unity-car-tutorials** [taylor001/crown#61]
The Pepper binary is non-functional under Ubuntu 14.04. Shaderc searches for GLIBCXX_3.4.21 which is not found even after libstdc++6 is installed. This results in the scene not loading properly.

There are also no instructions for building the tools, which are written Vala. Vala 0.22 and and libgee-0.8-dev were installed, but it doesn't compile, because there are errors related to Gio modules not being found.

**Comment by taylor001** [comment]
Can you upgrade to vala-0.32? Then:

    $ make tools-linux-debug64

**Comment by cl9dev** [comment]
Vala is unable to find gee.h or gtk.h, which on Ubuntu, are located in /usr/include/gee-0.8 and /usr/include/gtk-2.0 respectively

**Comment by taylor001** [comment]
$ apt-get install libgtk-3-dev

I added instructions here:
https://github.com/taylor001/crown#linux

**Comment by taylor001** [comment]
I've rebuilt binaries against an older GLIBCXX ABI. It should work out of the box now: https://github.com/taylor001/crown/#download

**Comment by cl9dev** [comment]
Yes, Pepper 0.21 now works on Ubuntu 14.04, thanks.

I still couldn't build the Crown tools via make. Is there somewhere in the project where I can specify the include directories for the different dependencies, i.e. GTK-3, Cairo, Pango, etc?

**Comment by taylor001** [comment]
Can you paste the output of `make tools-linux-debug64`?
