### ISSUE TITLE
genie/genie.lua syntax error: ")" unexpected. supposedly.

### ISSUE THREAD

**Issue by Kingsquee** [taylor001/crown#62]
```
~/Downloads/crown$ make engine-linux-release32

third/bx/tools/bin/linux/genie --file=genie/genie.lua --with-luajit --with-openal --with-bullet --with-tools --compiler=linux-gcc gmake

third/bx/tools/bin/linux/genie: 2: third/bx/tools/bin/linux/genie: Syntax error: ")" unexpected

make: *** [engine-linux-build] Error 2
```

For the life of me, I'm not seeing it.

**Comment by taylor001** [comment]
You either do `make engine-linux-release32` or call genie directly.

**Comment by Kingsquee** [comment]
Ah, that's what I did. Fixed the paste formatting.

**Comment by taylor001** [comment]
I cannot reproduce this. Is that 32-bit OS?

**Comment by Kingsquee** [comment]
Yup, 32bit Trisquel, which is based on Ubuntu LTS. Didn't get the error on my 64bit Fedora machine, it's quite strange.

**Comment by taylor001** [comment]
Genie is a 64-bit executable.

**Comment by Kingsquee** [comment]
Well that explains something.

**Comment by Kingsquee** [comment]
I take it this means crown only supports deployment to 32bit OS's?

**Comment by taylor001** [comment]
I've updated the manual, it should be clearer now.

However, development requires 64-bit, both for building *and* running the various engine parts.
Hardware requirements for target platforms really depend on the final product and should be determined by the manufacturer, I guess?

**Comment by Kingsquee** [comment]
Right, I see. The "Developing applications" section didn't have the same type of formatting as the "Deployment" section, so I skipped over reading it and found the system requirements ambiguous as to which (or both) it was referring to.

**Comment by taylor001** [comment]
:+1:

**Comment by Kingsquee** [comment]
#64?
