### ISSUE TITLE
Can you give example how to run the sample?

### ISSUE THREAD

**Issue by tomming** [taylor001/crown#65]
According to documentation, I have to specify --source-dir <path>, --data-dir <path> and --boot-dir <path>. However I have no idea where is the source and data folder? Can you give an example to run 00-empty sample entitled "00-empty"?

**Comment by taylor001** [comment]
I assume you cloned the repo to `/tmp/crown`.
$ make engine-linux-development64
$ cd /tmp/crown/build/engine/linux64/bin
$ ./crown-development-64 --source-dir /tmp/crown/samples/00-empty --data-dir /tmp/00-empty-data --map-source-dir core /tmp/crown/samples/00-empty
